Continuing the works for i18n and adding the Russian l10n

diff --git a/glacier b/glacier
--- a/glacier
+++ b/glacier
@@ -445,7 +445,7 @@ checkInventory()
 {
     COUNT=$(sql "SELECT count(1) FROM jobs WHERE vault_id = $VAULT_ID AND archive_id IS NULL AND status = $JST_INPROGRESS") #"
     if [ $COUNT == 0 ]; then
-	_ "Currently there is not any outstanding inventory requests"
+	_ "Currently there are no outstanding inventory requests"
 	return $E_FAIL
     fi
 
@@ -634,10 +634,10 @@ download() {
     ROWS=$(sql "$QUERY")
     if [ -z "$ROWS" ]; then
     	if [ -z "$1" ]; then
-	    _ "Какие-либо невыполненные задания на выгрузку файлов в каталоге отсутствует!"
+	    _ "Currently there are no outstanding download requests!"
 	else
-	    _ "Запрос(-ы) на выгрузку для указанного файла(-ов) в каталоге отсутствуют!"
-	    _ "Следует сначала запросить выгрузку файла(-ов) с помощью команды \"request\""
+	    _ "Currently there are no download requests for this file(s)!"
+	    _ "You should request the download with the \"request\" command"
 	fi
 	return $E_FAIL
     fi
@@ -650,7 +650,7 @@ download() {
 		--job-id="$JOB_ID" \
 	)
 	if [ $? != 0 ]; then
-	    _ "Неудача при попытке получить состояние задания!"
+	    _ "Job status request failed!"
 	    #sql "UPDATE jobs SET status = $JST_FAILED WHERE id = '$JOB_ID'"
 	    return $E_FAIL
 	fi
@@ -658,7 +658,7 @@ download() {
 	parseJson COMPLETED:Completed <<< "$REPLY"
 	trace "COMPLETED=$COMPLETED"
 	if [ "$COMPLETED" != "true" ]; then
-	    printf "$(_ "Запрос на выгрузку файла %s%s еще не выполнен, файл пропущен\n")" "$DIR" "$NAME"
+	    printf "$(_ "Download request for the file %s%s is not fulfilled yet, file skipped\n")" "$DIR" "$NAME"
 	    continue
 	fi
 
@@ -682,7 +682,7 @@ download() {
 	)
 	if [ $? != 0 ]; then
 	    echo
-	    printf "$(_ "Неудача при попытке выгрузить файл %s%s!\n")" "$DIR" "$NAME"
+	    printf "$(_ "Failure to download file %s%s!\n")" "$DIR" "$NAME"
 	    continue
 	fi
 
@@ -697,14 +697,14 @@ download() {
 purgeFiles() {
     COUNT=$(sql "SELECT count(1) FROM archives WHERE is_deleted")
     if [ $COUNT == 0 ]; then
-	_ "Удаленных файлов в каталоге не найдено"
+	_ "No deleted files found"
 	return $E_NOSUCHOBJECT
     fi
 
-    askYesNo "$(_ "Действительно вычистить все удаленные файлы? Вы уверены?")" || return $E_CANCELLED
+    askYesNo "$(_ "Really purge all deleted files? Are you sure?")" || return $E_CANCELLED
 
     sql "DELETE FROM archives WHERE is_deleted"
-    printf "$(_ "Вычищено %d удаленных файлов\n")" $COUNT
+    printf "$(_ "%d deleted files purged\n")" $COUNT
 } #purgeFiles
 
 
@@ -712,14 +712,14 @@ purgeFiles() {
 purgeJobs() {
     COUNT=$(sql "SELECT count(1) FROM jobs WHERE status <> 0")
     if [ $COUNT == 0 ]; then
-	_ "Выполненных заданий в каталоге не найдено"
+	_ "No completed jobs found"
 	return $E_NOSUCHOBJECT
     fi
 
-    askYesNo "$(_ "Действительно вычистить все выполненные задания ? Вы уверены?")" || return $E_CANCELLED
+    askYesNo "$(_ "Really purge all completed jobs? Are you sure?")" || return $E_CANCELLED
 
     sql "DELETE FROM jobs WHERE status <> 0"
-    printf "$(_ "Вычищено %s выполненных заданий\n")" $COUNT
+    printf "$(_ "%d completed jobs purged\n")" $COUNT
 } #purgeJobs
 
 
@@ -738,7 +738,7 @@ purge() {
 	    PURGE_JOBS=1
 	    ;;
 	*)
-	    _ "Необходимо указать, что вы хотите вычистить: files|jobs|all"
+	    _ "You should specify what are going to purge: files|jobs|all"
 	    return $E_FAIL
 	    ;;
     esac
@@ -749,7 +749,7 @@ purge() {
 
 
 initDB() {
-    echo -n $(_ "Инициализируем БД...")
+    echo -n $(_ "Initializing DB...")
     if sql "\
 	PRAGMA foreign_keys=ON;
 	CREATE TABLE vaults(id integer primary key, name text, arn text, inventory_time integer); \
@@ -773,7 +773,7 @@ initDB() {
 	echo
     else
 	echo
-	_ "Не могу проинициализировать базу данных!"
+	_ "Could not initialize DB!"
 	exit $E_FAIL
     fi
 } #initDB
@@ -784,33 +784,33 @@ showUsage() {
     echo
     echo $SCRIPT - $(_ "utility script for manipulation with AWS Glacier storage")
     echo
-    _    "  Варианты использования скрипта:"
-    echo "    $SCRIPT upload <FILE>,..          -- " $(_ "загрузить файл(-ы) в хранилище")
+    _    "  Usage:"
+    echo "    $SCRIPT upload <FILE>,..          -- " $(_ "sends file(s) to Glacier")
     echo "    $SCRIPT ls [-lLa] [<FILE>,..]     -- " $(_ "показать листинг каталога (что у нас уже загружено)")
-    echo "      -a                              -- " $(_ "показывать все файлы (в том числе и удаленные)")
+    echo "      -a               -- " $(_ "показывать все файлы (в том числе и удаленные)")
     echo "    $SCRIPT dir [-lLa] [<FILE>,..]    -- " $(_ "то же самое, что и \"ls\"")
     echo "    $SCRIPT rm <FILE>,..              -- " $(_ "удалить архив(-ы) из хранилища")
     echo "    $SCRIPT del <FILE>,..             -- " $(_ "то же самое, что и \"rm\"")
     echo "    $SCRIPT request <FILE>,..         -- " $(_ "запросить выгрузку файла(-ов) из хранилища")
     echo "    $SCRIPT request -                 -- " $(_ "запросить инвентаризацию хранилища")
     echo "    $SCRIPT download [-o] [<FILE>,..] -- " $(_ "выгрузить файла(-ов) из хранилища (после выполнения запроса)")
-    echo "      -o <OUT-FILE>                   -- " $(_ "выгрузить файл под другим именем/в другое место")
+    echo "      -o <OUT-FILE>    -- " $(_ "выгрузить файл под другим именем/в другое место")
     echo "    $SCRIPT inventory [-rflLс]        -- " $(_ "показать результаты инвентаризации")
-    echo "      -r                              -- " $(_ "запросить инвентаризацию, то же, что \"request -\"")
-    echo "      -f                              -- " $(_ "запросить новую инвентаризацию, даже если предыдущий запрос значится невыполненным")
-    echo "      -с                              -- " $(_ "проверить результат выполнения запроса и в случае успеха сохранить его в БД")
+    echo "      -r               -- " $(_ "запросить инвентаризацию, то же, что \"request -\"")
+    echo "      -f               -- " $(_ "запросить новую инвентаризацию, даже если предыдущий запрос значится невыполненным")
+    echo "      -с               -- " $(_ "проверить результат выполнения запроса и в случае успеха сохранить его в БД")
     echo "    $SCRIPT sync [-cy]                -- " $(_ "синхронизировать каталог с результатами последней инвентаризации")
-    echo "      -с                              -- " $(_ "выполнить проверку на расхождение, но не писать ничего в БД")
-    echo "      -y                              -- " $(_ "автоматически подразумевать положительный ответ на все вопросы")
+    echo "      -с               -- " $(_ "выполнить проверку на расхождение, но не писать ничего в БД")
+    echo "      -y               -- " $(_ "автоматически подразумевать положительный ответ на все вопросы")
     echo "    $SCRIPT jobs [-lLa]               -- " $(_ "показать список заданий на выгрузку файлов и инвентаризацию")
-    echo "      -a                              -- " $(_ "показывать все задания (в том числе и завершенные)")
+    echo "      -a               -- " $(_ "показывать все задания (в том числе и завершенные)")
     echo "    $SCRIPT purge files|jobs|all      -- " $(_ "вычистить из каталога удаленные файлы и/или выполненные задания")
     echo
        _ "  Общие ключи для всех команд:"
-    echo "      -d                              -- " $(_ "отладочный режим")
+    echo "      -d               -- " $(_ "отладочный режим")
        _ "  Общие ключи для команд листинга и инвентаризации:"
-    echo "      -l                              -- " $(_ "длинный режим листинга каталога или инвентаризации")
-    echo "      -L                              -- " $(_ "еще более длинный режим листинга каталога или инвентаризации")
+    echo "      -l               -- " $(_ "длинный режим листинга каталога или инвентаризации")
+    echo "      -L               -- " $(_ "еще более длинный режим листинга каталога или инвентаризации")
     echo
 } #showUsage
 
